### ISSUE TITLE
Improve UNINSTALL logic

### ISSUE THREAD

**Issue by robinjhuang** [Comfy-Org/desktop#89]
Add custom uninstall logic to Windows NSIS:

1. Should delete the `extra_model_config.yaml` file. This is always saved to `app.getPath('userData')`. 

Bonus: Read the file and the python environment located at "base_path". For example, it should delete everything under `/Users/junhanhuang/Documents/ComfyUI/.venv` and `/Users/junhanhuang/Documents/ComfyUI/uv-cache`

eg. 
```
# ComfyUI extra_model_paths.yaml for darwin
comfyui:
  base_path: /Users/junhanhuang/Documents/ComfyUI
  is_default: true
  checkpoints: models/checkpoints/
  classifiers: models/classifiers/
  clip: models/clip/
  clip_vision: models/clip_vision/
  configs: models/configs/
  controlnet: models/controlnet/
  diffusers: models/diffusers/
  diffusion_models: models/diffusion_models/
  embeddings: models/embeddings/
  gligen: models/gligen/
  hypernetworks: models/hypernetworks/
  loras: models/loras/
  photomaker: models/photomaker/
  style_models: models/style_models/
  unet: models/unet/
  upscale_models: models/upscale_models/
  vae: models/vae/
  vae_approx: models/vae_approx/
  custom_nodes: custom_nodes/

```

A development script that does this already exists in: https://github.com/Comfy-Org/electron/commit/8e55f5593a432cbd73155e5b288825fa7c1b35e5
